theme: jekyll-theme-cayman
show_downloads: false
logo: https://github.com/LeGitHubDeTai/TaiLauncher/blob/main/images/WarpedStemBEVersion.gif?raw=true
github:
  zip_url: https://github.com/LeGitHubDeTai/TaiLauncher/releases/download/v1.2.0/tailauncher.Setup.1.2.0.exe
  exe_url: https://github.com/LeGitHubDeTai/TaiLauncher/releases/download/v1.2.0/tailauncher.Setup.1.2.0.exe
